import { useEffect, useMemo, useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faArrowLeft, faChartLine, faDice, faRotate, faUsers } from '@fortawesome/free-solid-svg-icons';
import { AdminDashboardData, fetchAdminDashboard } from '../../services/admin';

const dateTime = (value: string | null) => value ? new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) : 'Never';

export default function AdminDashboard({ onClose, embedded = false }: { onClose?: () => void; embedded?: boolean }) {
  const [data, setData] = useState<AdminDashboardData | null>(null); const [error, setError] = useState(''); const [query, setQuery] = useState('');
  const load = () => { setError(''); void fetchAdminDashboard().then(setData).catch((caught) => setError(caught instanceof Error ? caught.message : 'Unable to load dashboard.')); };
  useEffect(load, []);
  const users = useMemo(() => data?.users.filter((user) => `${user.username} ${user.email} ${user.firstName} ${user.lastName}`.toLowerCase().includes(query.toLowerCase())) ?? [], [data?.users, query]);
  const maxGames = Math.max(1, ...(data?.dailyActivity.map((day) => day.games) ?? [1]));
  return <main className={embedded ? "site-page-content max-w-7xl" : "fixed inset-0 z-50 overflow-y-auto bg-deepBlack px-4 py-8 text-mintGlow sm:px-8"}><div className="mx-auto max-w-7xl">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Private workspace</p><h2 className="section-heading">Admin dashboard</h2><p className="section-copy">Registered accounts, gameplay activity and submitted results.</p></div><div className="flex gap-3"><button onClick={load} className="rounded-xl border border-neonCyan px-4 py-3 font-black text-neonCyan"><FontAwesomeIcon icon={faRotate} className="mr-2" />Refresh</button>{onClose && <button onClick={onClose} className="rounded-xl bg-neonCyan px-4 py-3 font-black text-deepBlack"><FontAwesomeIcon icon={faArrowLeft} className="mr-2" />Back to games</button>}</div></div>
    {!data && !error && <div className="web-panel mt-8 p-8 text-center"><FontAwesomeIcon icon={faRotate} spin className="mr-2" />Loading engagement…</div>}{error && <div className="web-panel mt-8 border-red-400 p-6 text-red-300"><strong>Dashboard unavailable</strong><p className="mt-2">{error}</p></div>}
    {data && <><div className="mt-8 grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Registered users', data.totalUsers, faUsers], ['Completed games', data.completedGames, faDice], ['Active · 7 days', data.activeUsersLast7Days, faChartLine], ['Games today', data.gamesToday, faDice]].map(([label, value, icon]) => <div key={String(label)} className="web-panel p-5"><FontAwesomeIcon icon={icon as any} className="text-electricPink" /><strong className="mt-3 block text-4xl text-neonYellow">{String(value)}</strong><small className="text-gray-400">{String(label)}</small></div>)}</div>
    <div className="mt-6 grid gap-4 lg:grid-cols-3"><section className="web-panel p-5 lg:col-span-2"><h3 className="text-xl font-black text-neonCyan">Daily activity</h3><p className="text-xs text-gray-500">Completed games and distinct players over 14 days</p><div className="mt-5 flex h-44 items-end gap-2">{data.dailyActivity.map((day) => <div key={day.date} className="group flex min-w-0 flex-1 flex-col items-center justify-end"><span className="mb-1 text-xs font-black text-neonYellow opacity-0 group-hover:opacity-100">{day.games}</span><div title={`${day.date}: ${day.games} games, ${day.players} players`} className="w-full rounded-t bg-neonCyan hover:bg-electricPink" style={{ height: `${Math.max(4, day.games / maxGames * 100)}%` }} /></div>)}</div></section><section className="web-panel p-5"><h3 className="text-xl font-black text-neonCyan">30-day snapshot</h3><dl className="mt-4 grid grid-cols-2 gap-4"><div><dt className="text-xs text-gray-500">Games</dt><dd className="text-2xl font-black">{data.gamesLast30Days}</dd></div><div><dt className="text-xs text-gray-500">Players</dt><dd className="text-2xl font-black">{data.activeUsersLast30Days}</dd></div><div><dt className="text-xs text-gray-500">Average score</dt><dd className="text-2xl font-black">{data.averageScore}</dd></div><div><dt className="text-xs text-gray-500">Yahtzees</dt><dd className="text-2xl font-black">{data.yahtzeesRolled}</dd></div></dl></section></div>
    <section className="web-panel mt-6 overflow-hidden"><div className="flex flex-wrap items-end justify-between gap-4 p-5"><div><h3 className="text-2xl font-black text-neonCyan">Users</h3><p className="text-sm text-gray-500">Last active means the latest completed game, not merely opening the app.</p></div><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search username or email" className="w-full rounded-xl border border-[#315a5e] bg-deepBlack px-4 py-3 text-white sm:w-80" /></div><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-[#142225] text-xs uppercase tracking-wider text-gray-400"><tr>{['Player','Account','Signed up','Last active','Games','Solo / Daily','Average / Best'].map((heading) => <th key={heading} className="px-4 py-3">{heading}</th>)}</tr></thead><tbody>{users.map((user) => <tr key={user.userId} className="border-t border-slate-800"><td className="px-4 py-4"><strong className="block text-mintGlow">{user.username || 'No username'}</strong><small className="text-gray-500">{user.firstName} {user.lastName}</small></td><td className="px-4 py-4"><span className="block text-white">{user.email}</span><small className={user.emailVerified ? 'text-green-400' : 'text-amber-400'}>{user.status} · {user.profileComplete ? 'Profile complete' : 'Onboarding incomplete'}</small></td><td className="px-4 py-4 text-gray-300">{dateTime(user.signedUpAt)}</td><td className="px-4 py-4 text-gray-300">{dateTime(user.lastPlayedAt)}</td><td className="px-4 py-4 font-black text-neonYellow">{user.gamesPlayed}</td><td className="px-4 py-4">{user.soloGames} / {user.dailyGames}</td><td className="px-4 py-4">{user.averageScore ?? '—'} / <b className="text-neonYellow">{user.bestScore ?? '—'}</b></td></tr>)}</tbody></table></div></section>
    <section className="web-panel mt-6 overflow-hidden"><div className="p-5"><h3 className="text-2xl font-black text-neonCyan">Recent score submissions</h3><p className="text-sm text-gray-500">The latest 50 completed Solo and Daily games.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-[#142225] text-xs uppercase text-gray-400"><tr><th className="px-4 py-3">Player</th><th className="px-4 py-3">Mode</th><th className="px-4 py-3">Score</th><th className="px-4 py-3">Submitted</th></tr></thead><tbody>{data.recentSubmissions.map((result) => <tr key={result.id} className="border-t border-slate-800"><td className="px-4 py-3 text-mintGlow">{result.username || result.userId}</td><td className="px-4 py-3">{result.mode}</td><td className="px-4 py-3 text-xl font-black text-neonYellow">{result.score}</td><td className="px-4 py-3 text-gray-300">{dateTime(result.completedAt)}</td></tr>)}</tbody></table></div></section><p className="py-5 text-right text-xs text-gray-600">Updated {dateTime(data.generatedAt)}</p></>}
  </div></main>;
}
