import { useEffect, useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faChartLine, faDice, faRotate, faUsers, faXmark } from '@fortawesome/free-solid-svg-icons';
import { AdminDashboardData, fetchAdminDashboard } from '../../services/admin';

export default function AdminDashboard({ onClose }: { onClose: () => void }) {
  const [data, setData] = useState<AdminDashboardData | null>(null);
  const [error, setError] = useState('');
  const load = () => { setError(''); void fetchAdminDashboard().then(setData).catch((caught) => setError(caught instanceof Error ? caught.message : 'Unable to load dashboard.')); };
  useEffect(load, []);
  const maxGames = Math.max(1, ...(data?.dailyActivity.map((day) => day.games) ?? [1]));
  return <div className="fixed inset-0 z-40 bg-black/75 backdrop-blur-sm" onClick={onClose}><aside role="dialog" aria-modal="true" aria-labelledby="admin-title" className="absolute right-0 top-0 h-full w-full max-w-3xl overflow-y-auto border-l border-electricPink bg-deepBlack p-5 sm:p-8" onClick={(event) => event.stopPropagation()}>
    <div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Private workspace</p><h2 id="admin-title" className="section-heading">Admin dashboard</h2><p className="section-copy">A live view of registered players and completed games.</p></div><button onClick={onClose} aria-label="Close admin dashboard" className="text-3xl text-neonCyan"><FontAwesomeIcon icon={faXmark} /></button></div>
    {!data && !error && <div className="web-panel mt-8 p-8 text-center text-mintGlow"><FontAwesomeIcon icon={faRotate} spin className="mr-2" />Loading engagement…</div>}
    {error && <div className="web-panel mt-8 border-red-400 p-6 text-red-300"><strong>Dashboard unavailable</strong><p className="mt-2 text-sm">{error}</p><button onClick={load} className="mt-4 font-black text-neonCyan">Try again</button></div>}
    {data && <><div className="mt-8 grid grid-cols-2 gap-3 md:grid-cols-4">
      {[['Registered players', data.totalUsers, faUsers], ['Completed games', data.completedGames, faDice], ['Active · 7 days', data.activeUsersLast7Days, faChartLine], ['Games today', data.gamesToday, faDice]].map(([label, value, icon]) => <div key={String(label)} className="web-panel p-4"><FontAwesomeIcon icon={icon as any} className="text-electricPink" /><strong className="mt-3 block text-3xl text-neonYellow">{String(value)}</strong><small className="text-gray-400">{String(label)}</small></div>)}
    </div><div className="mt-6 grid gap-4 md:grid-cols-2"><section className="web-panel p-5"><h3 className="text-xl font-black text-neonCyan">Engagement</h3><dl className="mt-4 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-gray-500">Games · 7 days</dt><dd className="text-2xl font-black text-white">{data.gamesLast7Days}</dd></div><div><dt className="text-gray-500">Games · 30 days</dt><dd className="text-2xl font-black text-white">{data.gamesLast30Days}</dd></div><div><dt className="text-gray-500">Active · 30 days</dt><dd className="text-2xl font-black text-white">{data.activeUsersLast30Days}</dd></div><div><dt className="text-gray-500">Average score</dt><dd className="text-2xl font-black text-white">{data.averageScore}</dd></div></dl></section><section className="web-panel p-5"><h3 className="text-xl font-black text-neonCyan">Gameplay</h3><dl className="mt-4 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-gray-500">Solo games</dt><dd className="text-2xl font-black text-white">{data.soloGames}</dd></div><div><dt className="text-gray-500">Daily games</dt><dd className="text-2xl font-black text-white">{data.dailyGames}</dd></div><div><dt className="text-gray-500">Yahtzees</dt><dd className="text-2xl font-black text-white">{data.yahtzeesRolled}</dd></div><div><dt className="text-gray-500">Upper bonuses</dt><dd className="text-2xl font-black text-white">{data.upperBonusesEarned}</dd></div></dl></section></div>
    <section className="web-panel mt-6 p-5"><div className="flex items-end justify-between"><div><h3 className="text-xl font-black text-neonCyan">Daily activity</h3><p className="text-xs text-gray-500">Completed games over the last 14 days</p></div><small className="text-gray-500">Updated {new Date(data.generatedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</small></div><div className="mt-5 flex h-44 items-end gap-2">{data.dailyActivity.map((day) => <div key={day.date} className="group flex min-w-0 flex-1 flex-col items-center justify-end"><span className="mb-1 text-xs font-black text-neonYellow opacity-0 group-hover:opacity-100">{day.games}</span><div title={`${day.date}: ${day.games} games, ${day.players} players`} className="w-full rounded-t bg-neonCyan transition hover:bg-electricPink" style={{ height: `${Math.max(4, day.games / maxGames * 100)}%` }} /><small className="mt-2 hidden rotate-[-45deg] text-[9px] text-gray-500 sm:block">{day.date.slice(5)}</small></div>)}</div></section></>}
  </aside></div>;
}
