name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Generate aws-exports.js
        run: |
          cat <<EOF > src/aws-exports.js
          const awsmobile = {
              "aws_project_region": "${{ secrets.REACT_APP_AWS_REGION }}",
              "aws_cognito_identity_pool_id": "${{ secrets.REACT_APP_USER_POOL_ID }}",
              "aws_cognito_region": "${{ secrets.REACT_APP_AWS_REGION }}",
              "aws_user_pools_id": "${{ secrets.REACT_APP_USER_POOL_ID }}",
              "aws_user_pools_web_client_id": "${{ secrets.REACT_APP_CLIENT_ID }}",
              "oauth": {},
              "aws_cognito_username_attributes": ["EMAIL"],
              "aws_cognito_signup_attributes": ["EMAIL"],
              "aws_cognito_mfa_configuration": "OFF",
              "aws_cognito_mfa_types": ["SMS"],
              "aws_cognito_password_protection_settings": {
                  "passwordPolicyMinLength": 8,
                  "passwordPolicyCharacters": []
              },
              "aws_cognito_verification_mechanisms": ["EMAIL"],
              "aws_appsync_graphqlEndpoint": "${{ secrets.REACT_APP_SYNC_GRAPHQLENDPOINT }}", done 
              "aws_appsync_region": "${{ secrets.REACT_APP_AWS_REGION }}",
              "aws_appsync_authenticationType": "API_KEY",
              "aws_appsync_apiKey": "${{ secrets.REACT_APP_APPSYNC_APIKEY }}" done 
          };

          export default awsmobile;
          EOF

      - name: Generate amplifyconfiguration.json
        run: |
          cat <<EOF > src/amplifyconfiguration.json
          {
            "aws_project_region": "${{ secrets.REACT_APP_AWS_REGION }}",
            "aws_user_pools_id": "${{ secrets.REACT_APP_USER_POOL_ID }}",
            "aws_user_pools_web_client_id": "${{ secrets.REACT_APP_CLIENT_ID }}"
          }
          EOF

      - name: Build Project
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Deploy to S3
        run: aws s3 sync ./build s3://yahtzeehub
